ScrollReveal().reveal('.footer__copyright', { reset: true, scale: .25 })
ScrollReveal().reveal('.footer__social--list', { reset: true, scale: .25 })
ScrollReveal().reveal('.topnav', { delay: 100, reset: true, scale: .5 })
ScrollReveal().reveal('#languages', { delay: 250, reset: true })
ScrollReveal().reveal('.project', { delay: 250, reset: true, scale: .85 })
ScrollReveal().reveal('.about-me__info', { delay: 250, reset: true, scale: .85 })
ScrollReveal().reveal('.row', { delay: 50, reset: true, scale: .9 })