ScrollReveal().reveal('.footer__copyright', { reset: true, scale: .25 })
ScrollReveal().reveal('.footer__social--list', { reset: true, scale: .25 })
ScrollReveal().reveal('.topnav', { delay: 100, reset: true, scale: .5 })
ScrollReveal().reveal('#languages', { delay: 250, reset: true })
ScrollReveal().reveal('.project', { delay: 250, reset: true, scale: .85 })
ScrollReveal().reveal('.about-me__info', { delay: 250, reset: true, scale: .85 })
ScrollReveal().reveal('.row', { delay: 50, reset: true, scale: .9 })
ScrollReveal().reveal('#about-me', { delay: 100, reset: false, scale: .25 })
ScrollReveal().reveal('#crescentico', { delay: 100, reset: false, scale: .5 })
ScrollReveal().reveal('#heartico', { delay: 350, reset: false, scale: .5 })
ScrollReveal().reveal('#dbico', { delay: 450, reset: false, scale: .5 })
ScrollReveal().reveal('#flower', { delay: 200, reset: false, scale: .5 })
ScrollReveal().reveal('#web', { delay: 150, reset: false, scale: .5 })
ScrollReveal().reveal('#line1', { delay: 300, reset: false, scale: .5 })
ScrollReveal().reveal('#line2', { delay: 250, reset: false, scale: .5 })
ScrollReveal().reveal('#cloudico', { delay: 500, reset: false, scale: .5 })
ScrollReveal().reveal('#blutri', { delay: 100, reset: false, scale: .5 })
